name: OpenMP C compiling and testing

on: [push]

jobs:
  build:

    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v1
    - name: Compile OpenMP test code and run it
      working-directory: ./
      run: |
        sudo apt-get update; sudo apt-get install -y libomp5 libomp-dev
        gcc omp_hello.c -fopenmp -o omp_hello
        ldd omp_hello
        ./omp_hello
